# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import server_services_pb2 as server__services__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server_services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SendFileServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFile = channel.unary_unary(
                '/server_services.SendFileService/SendFile',
                request_serializer=server__services__pb2.SendFileRequestBody.SerializeToString,
                response_deserializer=server__services__pb2.SendFileResponseBody.FromString,
                _registered_method=True)
        self.SendFileChunks = channel.stream_unary(
                '/server_services.SendFileService/SendFileChunks',
                request_serializer=server__services__pb2.SendFileChunksRequest.SerializeToString,
                response_deserializer=server__services__pb2.SendFileChunksResponse.FromString,
                _registered_method=True)
        self.ConvertCSVToXML = channel.unary_unary(
                '/server_services.SendFileService/ConvertCSVToXML',
                request_serializer=server__services__pb2.ConvertCSVToXMLRequest.SerializeToString,
                response_deserializer=server__services__pb2.ConvertCSVToXMLResponse.FromString,
                _registered_method=True)
        self.ValidateXML = channel.unary_unary(
                '/server_services.SendFileService/ValidateXML',
                request_serializer=server__services__pb2.ValidateXMLRequest.SerializeToString,
                response_deserializer=server__services__pb2.ValidateXMLResponse.FromString,
                _registered_method=True)
        self.TextSearch = channel.unary_unary(
                '/server_services.SendFileService/TextSearch',
                request_serializer=server__services__pb2.TextSearchRequest.SerializeToString,
                response_deserializer=server__services__pb2.TextSearchResponse.FromString,
                _registered_method=True)
        self.SortXML = channel.unary_unary(
                '/server_services.SendFileService/SortXML',
                request_serializer=server__services__pb2.SortXMLRequest.SerializeToString,
                response_deserializer=server__services__pb2.SortXMLResponse.FromString,
                _registered_method=True)
        self.ListXMLFiles = channel.unary_unary(
                '/server_services.SendFileService/ListXMLFiles',
                request_serializer=server__services__pb2.ListXMLFilesRequest.SerializeToString,
                response_deserializer=server__services__pb2.ListXMLFilesResponse.FromString,
                _registered_method=True)
        self.ListCSVFiles = channel.unary_unary(
                '/server_services.SendFileService/ListCSVFiles',
                request_serializer=server__services__pb2.ListCSVFilesRequest.SerializeToString,
                response_deserializer=server__services__pb2.ListCSVFilesResponse.FromString,
                _registered_method=True)


class SendFileServiceServicer(object):
    """Service definition
    """

    def SendFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFileChunks(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertCSVToXML(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateXML(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SortXML(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListXMLFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCSVFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendFileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFile,
                    request_deserializer=server__services__pb2.SendFileRequestBody.FromString,
                    response_serializer=server__services__pb2.SendFileResponseBody.SerializeToString,
            ),
            'SendFileChunks': grpc.stream_unary_rpc_method_handler(
                    servicer.SendFileChunks,
                    request_deserializer=server__services__pb2.SendFileChunksRequest.FromString,
                    response_serializer=server__services__pb2.SendFileChunksResponse.SerializeToString,
            ),
            'ConvertCSVToXML': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertCSVToXML,
                    request_deserializer=server__services__pb2.ConvertCSVToXMLRequest.FromString,
                    response_serializer=server__services__pb2.ConvertCSVToXMLResponse.SerializeToString,
            ),
            'ValidateXML': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateXML,
                    request_deserializer=server__services__pb2.ValidateXMLRequest.FromString,
                    response_serializer=server__services__pb2.ValidateXMLResponse.SerializeToString,
            ),
            'TextSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.TextSearch,
                    request_deserializer=server__services__pb2.TextSearchRequest.FromString,
                    response_serializer=server__services__pb2.TextSearchResponse.SerializeToString,
            ),
            'SortXML': grpc.unary_unary_rpc_method_handler(
                    servicer.SortXML,
                    request_deserializer=server__services__pb2.SortXMLRequest.FromString,
                    response_serializer=server__services__pb2.SortXMLResponse.SerializeToString,
            ),
            'ListXMLFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListXMLFiles,
                    request_deserializer=server__services__pb2.ListXMLFilesRequest.FromString,
                    response_serializer=server__services__pb2.ListXMLFilesResponse.SerializeToString,
            ),
            'ListCSVFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCSVFiles,
                    request_deserializer=server__services__pb2.ListCSVFilesRequest.FromString,
                    response_serializer=server__services__pb2.ListCSVFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_services.SendFileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('server_services.SendFileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SendFileService(object):
    """Service definition
    """

    @staticmethod
    def SendFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.SendFileService/SendFile',
            server__services__pb2.SendFileRequestBody.SerializeToString,
            server__services__pb2.SendFileResponseBody.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFileChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/server_services.SendFileService/SendFileChunks',
            server__services__pb2.SendFileChunksRequest.SerializeToString,
            server__services__pb2.SendFileChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertCSVToXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.SendFileService/ConvertCSVToXML',
            server__services__pb2.ConvertCSVToXMLRequest.SerializeToString,
            server__services__pb2.ConvertCSVToXMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.SendFileService/ValidateXML',
            server__services__pb2.ValidateXMLRequest.SerializeToString,
            server__services__pb2.ValidateXMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TextSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.SendFileService/TextSearch',
            server__services__pb2.TextSearchRequest.SerializeToString,
            server__services__pb2.TextSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SortXML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.SendFileService/SortXML',
            server__services__pb2.SortXMLRequest.SerializeToString,
            server__services__pb2.SortXMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListXMLFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.SendFileService/ListXMLFiles',
            server__services__pb2.ListXMLFilesRequest.SerializeToString,
            server__services__pb2.ListXMLFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCSVFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_services.SendFileService/ListCSVFiles',
            server__services__pb2.ListCSVFilesRequest.SerializeToString,
            server__services__pb2.ListCSVFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
